'use client';

/**
 * ExportOptionsPanel - Export options for the designer
 * Allows exporting as React component, HTML, or code snippets
 */

import { useCallback, useState } from 'react';
import { useTranslations } from 'next-intl';
import {
  Download,
  Copy,
  Check,
  FileCode,
  FileText,
  Braces,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Separator } from '@/components/ui/separator';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { TooltipProvider } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';
import { useDesignerStore } from '@/stores/designer';

type ExportFormat = 'react' | 'html' | 'jsx' | 'vue' | 'svelte';
type ExportStyle = 'tailwind' | 'css' | 'inline';

interface ExportConfig {
  format: ExportFormat;
  style: ExportStyle;
  includeComments: boolean;
  minify: boolean;
  typescript: boolean;
  componentName: string;
}

const DEFAULT_CONFIG: ExportConfig = {
  format: 'react',
  style: 'tailwind',
  includeComments: false,
  minify: false,
  typescript: true,
  componentName: 'MyComponent',
};

interface ExportOptionsPanelProps {
  className?: string;
  onExport?: (code: string, format: ExportFormat) => void;
}

export function ExportOptionsPanel({ className, onExport }: ExportOptionsPanelProps) {
  const t = useTranslations('designer');
  const [config, setConfig] = useState<ExportConfig>(DEFAULT_CONFIG);
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const code = useDesignerStore((state) => state.code);

  const updateConfig = (updates: Partial<ExportConfig>) => {
    setConfig((prev) => ({ ...prev, ...updates }));
  };

  // Generate export code based on config
  const generateExportCode = useCallback((): string => {
    let exportCode = code;

    // Wrap in React component if needed
    if (config.format === 'react') {
            const typeAnnotation = config.typescript ? ': React.FC' : '';
      
      exportCode = `${config.includeComments ? '// Generated by Cognia Designer\n\n' : ''}${config.typescript ? "import React from 'react';\n\n" : ''}export const ${config.componentName}${typeAnnotation} = () => {
  return (
    ${code.split('\n').map((line, i) => i === 0 ? line : '    ' + line).join('\n')}
  );
};

export default ${config.componentName};
`;
    } else if (config.format === 'html') {
      exportCode = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${config.componentName}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  ${code}
</body>
</html>`;
    } else if (config.format === 'vue') {
      exportCode = `<template>
  ${code}
</template>

<script setup${config.typescript ? ' lang="ts"' : ''}>
${config.includeComments ? '// Generated by Cognia Designer\n' : ''}
</script>`;
    } else if (config.format === 'svelte') {
      exportCode = `${config.includeComments ? '<!-- Generated by Cognia Designer -->\n\n' : ''}${code}

<style>
  /* Add your styles here */
</style>`;
    }

    // Minify if requested
    if (config.minify) {
      exportCode = exportCode
        .replace(/\s+/g, ' ')
        .replace(/>\s+</g, '><')
        .trim();
    }

    return exportCode;
  }, [code, config]);

  const handleCopy = useCallback(async () => {
    const exportCode = generateExportCode();
    await navigator.clipboard.writeText(exportCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [generateExportCode]);

  const handleExport = useCallback(async () => {
    setIsExporting(true);
    try {
      const exportCode = generateExportCode();
      
      // Create and download file
      const ext = {
        react: config.typescript ? 'tsx' : 'jsx',
        html: 'html',
        jsx: 'jsx',
        vue: 'vue',
        svelte: 'svelte',
      }[config.format];

      const blob = new Blob([exportCode], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${config.componentName}.${ext}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      onExport?.(exportCode, config.format);
    } finally {
      setIsExporting(false);
    }
  }, [generateExportCode, config.format, config.typescript, config.componentName, onExport]);

  const formatOptions = [
    { value: 'react', label: 'React', icon: <FileCode className="h-4 w-4" /> },
    { value: 'html', label: 'HTML', icon: <FileText className="h-4 w-4" /> },
    { value: 'vue', label: 'Vue', icon: <Braces className="h-4 w-4" /> },
    { value: 'svelte', label: 'Svelte', icon: <Braces className="h-4 w-4" /> },
  ];

  return (
    <TooltipProvider>
      <div className={cn('flex flex-col h-full', className)}>
        {/* Header */}
        <div className="border-b px-3 py-2">
          <div className="flex items-center gap-2">
            <Download className="h-4 w-4 text-muted-foreground" />
            <span className="text-sm font-medium">{t('exportOptions') || 'Export Options'}</span>
          </div>
        </div>

        <div className="flex-1 overflow-auto p-3 space-y-4">
          {/* Format selection */}
          <div className="space-y-2">
            <Label className="text-xs font-medium">{t('format') || 'Format'}</Label>
            <div className="grid grid-cols-2 gap-2">
              {formatOptions.map((option) => (
                <Button
                  key={option.value}
                  variant={config.format === option.value ? 'secondary' : 'outline'}
                  size="sm"
                  className="justify-start gap-2"
                  onClick={() => updateConfig({ format: option.value as ExportFormat })}
                >
                  {option.icon}
                  {option.label}
                </Button>
              ))}
            </div>
          </div>

          <Separator />

          {/* Style format */}
          <div className="space-y-2">
            <Label className="text-xs font-medium">{t('styleFormat') || 'Style Format'}</Label>
            <Select
              value={config.style}
              onValueChange={(v) => updateConfig({ style: v as ExportStyle })}
            >
              <SelectTrigger className="h-8">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="tailwind">Tailwind CSS</SelectItem>
                <SelectItem value="css">CSS Classes</SelectItem>
                <SelectItem value="inline">Inline Styles</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Component name (for React/Vue) */}
          {(config.format === 'react' || config.format === 'vue') && (
            <div className="space-y-2">
              <Label className="text-xs font-medium">{t('componentName') || 'Component Name'}</Label>
              <Input
                type="text"
                value={config.componentName}
                onChange={(e) => updateConfig({ componentName: e.target.value })}
                className="h-8"
                placeholder="MyComponent"
              />
            </div>
          )}

          <Separator />

          {/* Options */}
          <div className="space-y-3">
            <Label className="text-xs font-medium">{t('options') || 'Options'}</Label>
            
            {config.format === 'react' && (
              <div className="flex items-center justify-between">
                <span className="text-xs">{t('typescript') || 'TypeScript'}</span>
                <Switch
                  checked={config.typescript}
                  onCheckedChange={(v) => updateConfig({ typescript: v })}
                />
              </div>
            )}

            <div className="flex items-center justify-between">
              <span className="text-xs">{t('includeComments') || 'Include Comments'}</span>
              <Switch
                checked={config.includeComments}
                onCheckedChange={(v) => updateConfig({ includeComments: v })}
              />
            </div>

            <div className="flex items-center justify-between">
              <span className="text-xs">{t('minify') || 'Minify Output'}</span>
              <Switch
                checked={config.minify}
                onCheckedChange={(v) => updateConfig({ minify: v })}
              />
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="border-t p-3 space-y-2">
          <Button
            className="w-full"
            onClick={handleExport}
            disabled={isExporting}
          >
            <Download className="h-4 w-4 mr-2" />
            {t('downloadFile') || 'Download File'}
          </Button>
          
          <Button
            variant="outline"
            className="w-full"
            onClick={handleCopy}
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-2 text-green-500" />
                {t('copied') || 'Copied!'}
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 mr-2" />
                {t('copyToClipboard') || 'Copy to Clipboard'}
              </>
            )}
          </Button>
        </div>
      </div>
    </TooltipProvider>
  );
}

export default ExportOptionsPanel;
