/**
 * Marketplace Constants - Shared constants for marketplace components
 */

import React from 'react';
import {
  Grid3X3,
  Wrench,
  Layers,
  Zap,
  Code2,
  Palette,
  Terminal,
  LayoutGrid,
  FileCode2,
  Package,
  Shield,
  Sparkles,
  Clock,
  TrendingUp,
} from 'lucide-react';
import type { CategoryFilter, QuickFilter, PluginCollection, MarketplacePlugin } from './marketplace-types';

export const CATEGORY_INFO: Record<CategoryFilter, { icon: React.ElementType; label: string; color: string }> = {
  all: { icon: Grid3X3, label: 'All', color: 'bg-slate-500' },
  tools: { icon: Wrench, label: 'Tools', color: 'bg-blue-500' },
  components: { icon: Layers, label: 'Components', color: 'bg-purple-500' },
  modes: { icon: Zap, label: 'Modes', color: 'bg-amber-500' },
  skills: { icon: Code2, label: 'Skills', color: 'bg-emerald-500' },
  themes: { icon: Palette, label: 'Themes', color: 'bg-pink-500' },
  commands: { icon: Terminal, label: 'Commands', color: 'bg-cyan-500' },
  hooks: { icon: Code2, label: 'Hooks', color: 'bg-indigo-500' },
  processors: { icon: Code2, label: 'Processors', color: 'bg-orange-500' },
  providers: { icon: Code2, label: 'Providers', color: 'bg-teal-500' },
  exporters: { icon: Code2, label: 'Exporters', color: 'bg-rose-500' },
  importers: { icon: Code2, label: 'Importers', color: 'bg-lime-500' },
  a2ui: { icon: LayoutGrid, label: 'A2UI', color: 'bg-violet-500' },
  python: { icon: FileCode2, label: 'Python', color: 'bg-yellow-500' },
  scheduler: { icon: Clock, label: 'Scheduler', color: 'bg-sky-500' },
};

export const QUICK_FILTERS: { id: QuickFilter; label: string; icon: React.ElementType }[] = [
  { id: 'all', label: 'All', icon: Package },
  { id: 'verified', label: 'Verified', icon: Shield },
  { id: 'free', label: 'Free', icon: Sparkles },
  { id: 'new', label: 'New', icon: Clock },
  { id: 'popular', label: 'Popular', icon: TrendingUp },
];

export const PLUGIN_COLLECTIONS: PluginCollection[] = [
  {
    id: 'developer-essentials',
    name: 'Developer Essentials',
    description: 'Must-have plugins for developers',
    icon: Code2,
    pluginIds: ['cognia-web-search', 'git-assistant', 'api-tester'],
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'productivity-boost',
    name: 'Productivity Boost',
    description: 'Supercharge your workflow',
    icon: Zap,
    pluginIds: ['cognia-web-search', 'markdown-plus'],
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    id: 'creative-suite',
    name: 'Creative Suite',
    description: 'Tools for creative professionals',
    icon: Palette,
    pluginIds: ['theme-studio', 'ai-image-gen', 'data-visualizer'],
    gradient: 'from-purple-500 to-pink-500',
  },
];

export const MARKETPLACE_STATS = {
  totalPlugins: 1250,
  totalDownloads: 2800000,
  totalDevelopers: 450,
  weeklyNewPlugins: 28,
};

export const MOCK_PLUGINS: MarketplacePlugin[] = [
  {
    id: 'cognia-web-search',
    name: 'Web Search Plugin',
    description: 'Enhanced web search capabilities with multiple providers and result caching.',
    author: { name: 'Cognia Team', verified: true },
    version: '1.0.0',
    type: 'frontend',
    capabilities: ['tools', 'commands'],
    rating: 4.8,
    reviewCount: 1250,
    downloadCount: 45000,
    lastUpdated: '2024-01-20',
    tags: ['search', 'web', 'ai', 'productivity'],
    featured: true,
    verified: true,
  },
  {
    id: 'code-analyzer',
    name: 'Code Analyzer',
    description: 'Static code analysis with security scanning, performance suggestions, and best practices recommendations.',
    author: { name: 'DevTools Inc', verified: true },
    version: '1.5.2',
    type: 'python',
    capabilities: ['tools', 'processors'],
    rating: 4.6,
    reviewCount: 890,
    downloadCount: 32000,
    lastUpdated: '2024-01-10',
    tags: ['code', 'analysis', 'security', 'developer'],
    trending: true,
    verified: true,
  },
  {
    id: 'theme-studio',
    name: 'Theme Studio',
    description: 'Create and customize beautiful themes with live preview, color palettes, and export options.',
    author: { name: 'UI Masters' },
    version: '3.0.0',
    type: 'frontend',
    capabilities: ['themes', 'components'],
    rating: 4.9,
    reviewCount: 2100,
    downloadCount: 78000,
    lastUpdated: '2024-01-18',
    tags: ['themes', 'ui', 'design', 'customization'],
    featured: true,
    verified: true,
  },
  {
    id: 'data-visualizer',
    name: 'Data Visualizer',
    description: 'Transform your data into stunning interactive charts, graphs, and dashboards.',
    author: { name: 'DataViz Labs' },
    version: '2.3.1',
    type: 'frontend',
    capabilities: ['components', 'a2ui'],
    rating: 4.7,
    reviewCount: 650,
    downloadCount: 28000,
    lastUpdated: '2024-01-12',
    tags: ['data', 'visualization', 'charts', 'dashboard'],
    trending: true,
  },
  {
    id: 'git-assistant',
    name: 'Git Assistant',
    description: 'AI-powered Git workflow assistant with commit suggestions, PR reviews, and conflict resolution.',
    author: { name: 'GitFlow Team', verified: true },
    version: '1.8.0',
    type: 'hybrid',
    capabilities: ['tools', 'commands', 'hooks'],
    rating: 4.5,
    reviewCount: 420,
    downloadCount: 15000,
    lastUpdated: '2024-01-08',
    tags: ['git', 'version-control', 'ai', 'developer'],
  },
  {
    id: 'markdown-plus',
    name: 'Markdown Plus',
    description: 'Enhanced markdown editing with live preview, templates, and export to multiple formats.',
    author: { name: 'Doc Writers' },
    version: '1.2.0',
    type: 'frontend',
    capabilities: ['components', 'exporters'],
    rating: 4.4,
    reviewCount: 380,
    downloadCount: 22000,
    lastUpdated: '2024-01-05',
    tags: ['markdown', 'editor', 'documentation'],
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Comprehensive API testing tool with request builder, response validation, and automation.',
    author: { name: 'API Tools Co' },
    version: '2.0.5',
    type: 'hybrid',
    capabilities: ['tools', 'commands'],
    rating: 4.6,
    reviewCount: 560,
    downloadCount: 19000,
    lastUpdated: '2024-01-14',
    tags: ['api', 'testing', 'developer', 'automation'],
  },
  {
    id: 'ai-image-gen',
    name: 'AI Image Generator',
    description: 'Generate stunning images from text prompts using state-of-the-art AI models.',
    author: { name: 'AI Arts', verified: true },
    version: '1.0.0',
    type: 'python',
    capabilities: ['tools', 'a2ui'],
    rating: 4.9,
    reviewCount: 3200,
    downloadCount: 125000,
    lastUpdated: '2024-01-20',
    tags: ['ai', 'image', 'generation', 'creative'],
    featured: true,
    trending: true,
    verified: true,
  },
];
