/**
 * Marketplace Mock Data - Isolated for tree-shaking
 * 
 * This file contains mock data used for development and fallback when the API is unavailable.
 * It is separated from constants to enable tree-shaking in production builds.
 */

import type { MarketplacePlugin } from './marketplace-types';

export const MOCK_REVIEWS: MarketplacePlugin['reviews'] = [
  {
    id: '1',
    author: 'John Developer',
    rating: 5,
    date: '2024-01-18',
    content: 'Excellent plugin! Really improved my workflow. The AI features are incredibly accurate and helpful.',
    helpful: 24,
  },
  {
    id: '2',
    author: 'Sarah Designer',
    rating: 4,
    date: '2024-01-15',
    content: 'Great functionality, but could use some UI improvements. Overall very useful for daily tasks.',
    helpful: 12,
  },
  {
    id: '3',
    author: 'Mike Engineer',
    rating: 5,
    date: '2024-01-10',
    content: 'This is exactly what I needed. Integration was seamless and it just works. Highly recommended!',
    helpful: 18,
  },
];

export const MOCK_CHANGELOG: MarketplacePlugin['changelog'] = [
  {
    version: '2.1.0',
    date: '2024-01-15',
    changes: [
      'Added new AI-powered suggestions',
      'Improved performance by 40%',
      'Fixed bug with large files',
      'Updated UI components',
    ],
  },
  {
    version: '2.0.0',
    date: '2024-01-01',
    changes: [
      'Complete redesign of the interface',
      'New configuration system',
      'Breaking: Changed API endpoints',
    ],
    breaking: true,
  },
  {
    version: '1.5.2',
    date: '2023-12-15',
    changes: [
      'Fixed memory leak issue',
      'Added support for dark mode',
      'Minor bug fixes',
    ],
  },
];

export const MOCK_PLUGINS: MarketplacePlugin[] = [
  {
    id: 'cognia-web-search',
    name: 'Web Search Plugin',
    description: 'Enhanced web search capabilities with multiple providers and result caching.',
    author: { name: 'Cognia Team', verified: true, url: 'https://cognia.app' },
    version: '1.0.0',
    type: 'frontend',
    capabilities: ['tools', 'commands'],
    rating: 4.8,
    reviewCount: 1250,
    downloadCount: 45000,
    lastUpdated: '2024-01-20',
    tags: ['search', 'web', 'ai', 'productivity'],
    featured: true,
    verified: true,
    repository: 'https://github.com/cognia-app/web-search-plugin',
    homepage: 'https://cognia.app/plugins/web-search',
    documentation: 'https://docs.cognia.app/plugins/web-search',
    license: 'MIT',
    ratingBreakdown: { 5: 72, 4: 18, 3: 6, 2: 3, 1: 1 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'code-analyzer',
    name: 'Code Analyzer',
    description: 'Static code analysis with security scanning, performance suggestions, and best practices recommendations.',
    author: { name: 'DevTools Inc', verified: true },
    version: '1.5.2',
    type: 'python',
    capabilities: ['tools', 'processors'],
    rating: 4.6,
    reviewCount: 890,
    downloadCount: 32000,
    lastUpdated: '2024-01-10',
    tags: ['code', 'analysis', 'security', 'developer'],
    trending: true,
    verified: true,
    repository: 'https://github.com/devtools-inc/code-analyzer',
    license: 'Apache-2.0',
    ratingBreakdown: { 5: 55, 4: 28, 3: 10, 2: 5, 1: 2 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'theme-studio',
    name: 'Theme Studio',
    description: 'Create and customize beautiful themes with live preview, color palettes, and export options.',
    author: { name: 'UI Masters' },
    version: '3.0.0',
    type: 'frontend',
    capabilities: ['themes', 'components'],
    rating: 4.9,
    reviewCount: 2100,
    downloadCount: 78000,
    lastUpdated: '2024-01-18',
    tags: ['themes', 'ui', 'design', 'customization'],
    featured: true,
    verified: true,
    homepage: 'https://uimasters.dev/theme-studio',
    license: 'MIT',
    ratingBreakdown: { 5: 80, 4: 12, 3: 5, 2: 2, 1: 1 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'data-visualizer',
    name: 'Data Visualizer',
    description: 'Transform your data into stunning interactive charts, graphs, and dashboards.',
    author: { name: 'DataViz Labs' },
    version: '2.3.1',
    type: 'frontend',
    capabilities: ['components', 'a2ui'],
    rating: 4.7,
    reviewCount: 650,
    downloadCount: 28000,
    lastUpdated: '2024-01-12',
    tags: ['data', 'visualization', 'charts', 'dashboard'],
    trending: true,
    repository: 'https://github.com/dataviz-labs/data-visualizer',
    license: 'MIT',
    ratingBreakdown: { 5: 65, 4: 22, 3: 8, 2: 3, 1: 2 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'git-assistant',
    name: 'Git Assistant',
    description: 'AI-powered Git workflow assistant with commit suggestions, PR reviews, and conflict resolution.',
    author: { name: 'GitFlow Team', verified: true },
    version: '1.8.0',
    type: 'hybrid',
    capabilities: ['tools', 'commands', 'hooks'],
    rating: 4.5,
    reviewCount: 420,
    downloadCount: 15000,
    lastUpdated: '2024-01-08',
    tags: ['git', 'version-control', 'ai', 'developer'],
    repository: 'https://github.com/gitflow-team/git-assistant',
    license: 'MIT',
    ratingBreakdown: { 5: 50, 4: 30, 3: 12, 2: 5, 1: 3 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'markdown-plus',
    name: 'Markdown Plus',
    description: 'Enhanced markdown editing with live preview, templates, and export to multiple formats.',
    author: { name: 'Doc Writers' },
    version: '1.2.0',
    type: 'frontend',
    capabilities: ['components', 'exporters'],
    rating: 4.4,
    reviewCount: 380,
    downloadCount: 22000,
    lastUpdated: '2024-01-05',
    tags: ['markdown', 'editor', 'documentation'],
    license: 'MIT',
    ratingBreakdown: { 5: 45, 4: 32, 3: 15, 2: 5, 1: 3 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Comprehensive API testing tool with request builder, response validation, and automation.',
    author: { name: 'API Tools Co' },
    version: '2.0.5',
    type: 'hybrid',
    capabilities: ['tools', 'commands'],
    rating: 4.6,
    reviewCount: 560,
    downloadCount: 19000,
    lastUpdated: '2024-01-14',
    tags: ['api', 'testing', 'developer', 'automation'],
    repository: 'https://github.com/api-tools-co/api-tester',
    license: 'Apache-2.0',
    ratingBreakdown: { 5: 58, 4: 25, 3: 10, 2: 4, 1: 3 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
  {
    id: 'ai-image-gen',
    name: 'AI Image Generator',
    description: 'Generate stunning images from text prompts using state-of-the-art AI models.',
    author: { name: 'AI Arts', verified: true },
    version: '1.0.0',
    type: 'python',
    capabilities: ['tools', 'a2ui'],
    rating: 4.9,
    reviewCount: 3200,
    downloadCount: 125000,
    lastUpdated: '2024-01-20',
    tags: ['ai', 'image', 'generation', 'creative'],
    featured: true,
    trending: true,
    verified: true,
    homepage: 'https://aiarts.dev',
    documentation: 'https://docs.aiarts.dev',
    license: 'MIT',
    ratingBreakdown: { 5: 78, 4: 14, 3: 5, 2: 2, 1: 1 },
    reviews: MOCK_REVIEWS,
    changelog: MOCK_CHANGELOG,
  },
];
