export type SettingsSection =
  | 'providers'
  | 'chat'
  | 'mcp'
  | 'tools'
  | 'skills'
  | 'plugins'
  | 'instructions'
  | 'memory'
  | 'usage'
  | 'appearance'
  | 'response'
  | 'keyboard'
  | 'speech'
  | 'search'
  | 'data'
  | 'vector'
  | 'desktop'
  | 'environment'
  | 'proxy'
  | 'selection'
  | 'native-tools'
  | 'prompt-templates'
  | 'prompt-marketplace'
  | 'sandbox'
  | 'git'
  | 'safety'
  | 'observability';

export type SettingsGroup = 'ai' | 'interface' | 'data' | 'system';
