/**
 * AI module exports
 *
 * This module provides unified AI functionality using Vercel AI SDK:
 * - Multi-provider client support (OpenAI, Anthropic, Google, etc.)
 * - Provider registry for intelligent routing
 * - Middleware for caching, retry, reasoning extraction
 * - Structured output generation
 * - RAG (Retrieval Augmented Generation)
 * - Agent execution with tool calling
 * - Image generation and processing
 * - Rate limiting and caching
 * - Sequential generation workflows
 *
 * Based on AI SDK v5+ best practices
 */

// Core - Client, providers, registry, middleware
export * from './core';

// Providers - Ollama, OpenRouter, OAuth
export * from './providers';

// Generation - Chat, structured output, summarization
export * from './generation';

// Embedding - Embeddings, chunking, compression
export * from './embedding';

// Media - Image, video, speech
export * from './media';

// Infrastructure - Rate limiting, caching, telemetry
export * from './infrastructure';

// Tools - Note: Selective re-exports to avoid conflicts
export {
  ARTIFACT_SUPPORTED_LANGUAGES,
} from './tools';
export type { ToolDefinition, ToolRegistry, ToolFunction } from './tools';

// Re-export everything else from tools except conflicting names
export {
  webSearchTool,
  executeWebSearch,
  webSearchInputSchema,
  type WebSearchToolInput,
  type WebSearchResult,
  type WebSearchConfig,
  webScraperTool,
  bulkWebScraperTool,
  searchAndScrapeTool,
  executeWebScraper,
  executeBulkWebScraper,
  executeSearchAndScrape,
  webScraperInputSchema,
  bulkWebScraperInputSchema,
  searchAndScraperInputSchema,
  type WebScraperInput,
  type BulkWebScraperInput,
  type SearchAndScrapeInput,
  type WebScraperResult,
  type BulkWebScraperResult,
  type SearchAndScrapeResult,
  ragSearchTool,
  executeRAGSearch,
  ragSearchInputSchema,
  type RAGSearchInput,
  type RAGSearchResult,
  academicSearchTool,
  executeAcademicSearch,
  academicSearchInputSchema,
  formatAcademicResultsForAI,
  type AcademicSearchInput,
  type AcademicSearchResult,
  type AcademicSearchConfig,
  academicAnalysisTool,
  executeAcademicAnalysis,
  academicAnalysisInputSchema,
  buildAnalysisPrompt,
  formatPaperForAnalysis,
  paperComparisonTool,
  executePaperComparison,
  paperComparisonInputSchema,
  type AcademicAnalysisInput,
  type AcademicAnalysisResult,
  type PaperComparisonInput,
  type PaperComparisonResult,
  calculatorTool,
  executeCalculator,
  calculatorInputSchema,
  convertUnit,
  unitConversions,
  type CalculatorInput,
  type CalculatorResult,
  documentTools,
  executeDocumentSummarize,
  executeDocumentChunk,
  executeDocumentAnalyze,
  type DocumentToolResult,
  fileTools,
  executeFileRead,
  executeFileWrite,
  executeFileList,
  executeFileExists,
  executeFileDelete,
  executeDirectoryCreate,
  executeFileCopy,
  executeFileRename,
  executeFileInfo,
  executeFileSearch,
  executeFileAppend,
  fileReadInputSchema,
  fileWriteInputSchema,
  fileListInputSchema,
  fileExistsInputSchema,
  fileDeleteInputSchema,
  directoryCreateInputSchema,
  fileCopyInputSchema,
  fileRenameInputSchema,
  fileInfoInputSchema,
  fileSearchInputSchema,
  fileAppendInputSchema,
  type FileReadInput,
  type FileWriteInput,
  type FileListInput,
  type FileExistsInput,
  type FileDeleteInput,
  type DirectoryCreateInput,
  type FileCopyInput,
  type FileRenameInput,
  type FileInfoInput,
  type FileSearchInput,
  type FileAppendInput,
  type FileToolResult,
  pptTools,
  executePPTOutline,
  executePPTSlideContent,
  executePPTFinalize,
  executePPTExport,
  registerPPTTools,
  pptOutlineInputSchema,
  pptSlideContentInputSchema,
  pptFinalizeInputSchema,
  pptExportInputSchema,
  type PPTOutlineInput,
  type PPTSlideContentInput,
  type PPTFinalizeInput,
  type PPTExportInput,
  type PPTToolResult,
  createPPTGenerationTool,
  detectPPTGenerationIntent,
  buildPPTSuggestionResponse,
  pptGenerationInputSchema,
  type PPTGenerationInput,
  type PPTGenerationResult,
  type PPTGenerationCallback,
  materialTools,
  executeMaterialExtract,
  executeMaterialSummarize,
  executeMaterialAnalyze,
  executeMaterialCombine,
  registerMaterialTools,
  materialExtractInputSchema,
  materialSummarizeInputSchema,
  materialAnalyzeInputSchema,
  materialCombineInputSchema,
  generateSummarizationPrompt,
  generateAnalysisPrompt,
  type MaterialExtractInput,
  type MaterialSummarizeInput,
  type MaterialAnalyzeInput,
  type MaterialCombineInput,
  type MaterialToolResult,
  slideImageTools,
  executeSlideImageGenerate,
  executeSlideBatchImageGenerate,
  executeSlideImagePromptGenerate,
  enhanceSlidesWithImages,
  registerSlideImageTools,
  slideImageGenerateInputSchema,
  slideBatchImageGenerateInputSchema,
  slideImagePromptGenerateInputSchema,
  type SlideImageGenerateInput,
  type SlideBatchImageGenerateInput,
  type SlideImagePromptGenerateInput,
  type SlideImageToolResult,
  pptImageTools,
  executePPTImageGenerate,
  executePPTBatchImageGenerate,
  buildImagePrompt,
  applyImagesToSlides,
  registerPPTImageTools,
  pptImageGenerateInputSchema,
  pptBatchImageGenerateInputSchema,
  type PPTImageGenerateInput,
  type PPTBatchImageGenerateInput,
  type PPTImageToolResult,
  videoTools,
  videoGenerateTool,
  videoStatusTool,
  executeVideoGenerate,
  executeVideoStatus,
  executeGetVideoModels,
  registerVideoTools,
  videoGenerateInputSchema,
  videoStatusInputSchema,
  type VideoGenerateInput,
  type VideoStatusInput,
  type VideoToolResult,
  videoAnalysisTools,
  videoSubtitleTool,
  videoAnalysisTool,
  subtitleParseTool,
  executeVideoSubtitleExtraction,
  executeVideoAnalysis,
  executeSubtitleParse,
  formatVideoAnalysisForAI,
  registerVideoAnalysisTools,
  videoSubtitleInputSchema,
  videoAnalysisInputSchema,
  subtitleParseInputSchema,
  type VideoSubtitleInput,
  type VideoAnalysisInput,
  type SubtitleParseInput,
  type VideoAnalysisToolResult,
  imageTools,
  imageGenerateTool,
  imageEditTool,
  imageVariationTool,
  executeImageGenerate,
  executeImageEdit,
  executeImageVariation,
  executeGetImageModels,
  executeEstimateCost,
  registerImageTools,
  imageGenerateInputSchema,
  imageEditInputSchema,
  imageVariationInputSchema,
  type ImageGenerateInput,
  type ImageEditInput,
  type ImageVariationInput,
  type ImageToolResult,
  learningTools,
  learningToolsByCanonicalName,
  LEARNING_TOOL_CANONICAL_NAMES,
  LEARNING_TOOL_ALIASES,
  LEARNING_TOOL_CANONICAL_TO_ALIAS,
  normalizeLearningToolName,
  toLearningToolAliasName,
  isLearningToolName,
  executeDisplayFlashcard,
  executeDisplayFlashcardDeck,
  executeDisplayQuiz,
  executeDisplayQuizQuestion,
  executeDisplayReviewSession,
  executeDisplayProgressSummary,
  executeDisplayConceptExplanation,
  executeDisplayStepGuide,
  executeDisplayConceptMap,
  executeDisplayAnimation,
  flashcardSchema,
  quizQuestionSchema,
  quizSchema,
  reviewSessionSchema,
  displayFlashcardInputSchema,
  displayFlashcardDeckInputSchema,
  displayQuizInputSchema,
  displayQuizQuestionInputSchema,
  displayReviewSessionInputSchema,
  displayProgressSummaryInputSchema,
  displayConceptExplanationInputSchema,
  displayStepGuideInputSchema,
  displayConceptMapInputSchema,
  displayAnimationInputSchema,
  type FlashcardData,
  type QuizQuestionData,
  type QuizData,
  type ReviewSessionData,
  type CanonicalLearningToolName,
  type LearningToolAliasName,
  type LearningToolName,
  type DisplayFlashcardInput,
  type DisplayFlashcardDeckInput,
  type DisplayQuizInput,
  type DisplayQuizQuestionInput,
  type DisplayReviewSessionInput,
  type DisplayProgressSummaryInput,
  type DisplayConceptExplanationInput,
  type DisplayStepGuideInput,
  type DisplayConceptMapInput,
  type DisplayAnimationInput,
  type FlashcardToolOutput,
  type FlashcardDeckToolOutput,
  type QuizToolOutput,
  type QuizQuestionToolOutput,
  type ReviewSessionToolOutput,
  type ProgressSummaryToolOutput,
  type ConceptExplanationToolOutput,
  type StepGuideToolOutput,
  type ConceptMapToolOutput,
  type AnimationToolOutput,
  type LearningToolOutput,
  UnifiedToolRegistry,
  getUnifiedToolRegistry,
  setUnifiedToolRegistry,
  registerBuiltinTools,
  registerSkillTools,
  registerMcpTools,
  registerCustomTools,
  inferToolCategory,
  type ToolSource,
  type ToolMetadata,
  type ToolRegistrationMetadata,
  type RegisteredTool,
  type ToolRegistryConfig,
  type ToolFilterOptions,
  detectUserIntent,
  detectChatIntent,
  detectModeMismatch,
  getModeSwitchSuggestion,
  shouldSuggestModeSwitch,
  getEnhancedModeSuggestion,
  type IntentDetectionResult,
  artifactTools,
  artifactCreateTool,
  artifactUpdateTool,
  artifactReadTool,
  artifactSearchTool,
  artifactRenderTool,
  artifactExportTool,
  artifactDeleteTool,
  executeArtifactCreate,
  executeArtifactUpdate,
  executeArtifactRead,
  executeArtifactSearch,
  executeArtifactRender,
  executeArtifactExport,
  executeArtifactDelete,
  registerArtifactTools,
  getArtifactToolsPrompt,
  artifactCreateInputSchema,
  artifactUpdateInputSchema,
  artifactReadInputSchema,
  artifactSearchInputSchema,
  artifactRenderInputSchema,
  artifactExportInputSchema,
  artifactDeleteInputSchema,
  ARTIFACT_TYPES,
  type ArtifactCreateInput,
  type ArtifactUpdateInput,
  type ArtifactReadInput,
  type ArtifactSearchInput,
  type ArtifactRenderInput,
  type ArtifactExportInput,
  type ArtifactDeleteInput,
  type ArtifactToolResult,
  memoryTools,
  memoryStoreTool,
  memoryRecallTool,
  memorySearchTool,
  memoryDeleteTool,
  memoryListTool,
  memoryUpdateTool,
  executeMemoryStore,
  executeMemoryRecall,
  executeMemorySearch,
  executeMemoryDelete,
  executeMemoryList,
  executeMemoryUpdate,
  registerMemoryTools,
  getMemoryToolsPrompt,
  memoryStoreInputSchema,
  memoryRecallInputSchema,
  memorySearchInputSchema,
  memoryDeleteInputSchema,
  memoryListInputSchema,
  memoryUpdateInputSchema,
  type MemoryStoreInput,
  type MemoryRecallInput,
  type MemorySearchInput,
  type MemoryDeleteInput,
  type MemoryListInput,
  type MemoryUpdateInput,
  type MemoryToolResult,
} from './tools';

// RAG
export * from './rag';

// Memory
export * from './memory';

// Agent system
export * from './agent';

// Workflows
export * from './workflows';

// Context budget
export { computeBudget, segmentHeadroom, isCompressionRecommended } from './context-budget';
export type { BudgetInput, BudgetAllocation } from './context-budget';
