/**
 * .gitignore Templates
 *
 * Pre-defined templates for common project types
 */

export interface GitignoreTemplate {
  id: string;
  name: string;
  description: string;
  icon?: string;
  content: string;
}

/**
 * Node.js / JavaScript / TypeScript template
 */
const nodeTemplate: GitignoreTemplate = {
  id: 'node',
  name: 'Node.js',
  description: 'Node.js, npm, yarn, pnpm projects',
  icon: '🟢',
  content: `# Dependencies
node_modules/
.pnp/
.pnp.js

# Build outputs
dist/
build/
out/
.next/
.nuxt/
.output/

# Cache
.cache/
.parcel-cache/
.turbo/
.vercel/
.netlify/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Testing
coverage/
.nyc_output/

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Package manager locks (keep one)
# package-lock.json
# yarn.lock
# pnpm-lock.yaml
`,
};

/**
 * Python template
 */
const pythonTemplate: GitignoreTemplate = {
  id: 'python',
  name: 'Python',
  description: 'Python, pip, virtualenv, Django, Flask',
  icon: '🐍',
  content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/
.venv/

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Django stuff
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff
instance/
.webassets-cache

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# Environments
.env
.env.local

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
`,
};

/**
 * Rust template
 */
const rustTemplate: GitignoreTemplate = {
  id: 'rust',
  name: 'Rust',
  description: 'Rust, Cargo projects',
  icon: '🦀',
  content: `# Generated by Cargo
/target/
debug/
release/

# Cargo.lock is usually tracked for binaries
# Cargo.lock

# Build dependencies
/target/
**/*.rs.bk

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
`,
};

/**
 * React / Next.js template
 */
const reactTemplate: GitignoreTemplate = {
  id: 'react',
  name: 'React / Next.js',
  description: 'React, Next.js, Create React App',
  icon: '⚛️',
  content: `# Dependencies
node_modules/
.pnp/
.pnp.js

# Build outputs
dist/
build/
out/
.next/
.vercel/

# Testing
coverage/

# Production
/build

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
next-env.d.ts

# IDE
.idea/
.vscode/
*.swp
*.swo
*~
`,
};

/**
 * Tauri template
 */
const tauriTemplate: GitignoreTemplate = {
  id: 'tauri',
  name: 'Tauri',
  description: 'Tauri desktop applications',
  icon: '🖥️',
  content: `# Dependencies
node_modules/
.pnp/
.pnp.js

# Build outputs
dist/
build/
out/
.next/

# Rust/Tauri
/src-tauri/target/
/src-tauri/WixTools/
/src-tauri/gen/

# Cache
.cache/
.turbo/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Testing
coverage/

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
`,
};

/**
 * Go template
 */
const goTemplate: GitignoreTemplate = {
  id: 'go',
  name: 'Go',
  description: 'Go / Golang projects',
  icon: '🐹',
  content: `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with \`go test -c\`
*.test

# Output of the go coverage tool
*.out

# Dependency directories
vendor/

# Go workspace file
go.work

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
`,
};

/**
 * Java template
 */
const javaTemplate: GitignoreTemplate = {
  id: 'java',
  name: 'Java',
  description: 'Java, Maven, Gradle projects',
  icon: '☕',
  content: `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle/
build/
!**/src/main/**/build/
!**/src/test/**/build/

# IDE
.idea/
*.iws
*.iml
*.ipr
.eclipse/
.settings/
.project
.classpath
.vscode/

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
`,
};

/**
 * Minimal template
 */
const minimalTemplate: GitignoreTemplate = {
  id: 'minimal',
  name: 'Minimal',
  description: 'Basic gitignore for any project',
  icon: '📄',
  content: `# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local

# Logs
*.log
logs/
`,
};

/**
 * All available gitignore templates
 */
export const gitignoreTemplates: GitignoreTemplate[] = [
  nodeTemplate,
  pythonTemplate,
  rustTemplate,
  reactTemplate,
  tauriTemplate,
  goTemplate,
  javaTemplate,
  minimalTemplate,
];

/**
 * Get a template by ID
 */
export function getGitignoreTemplate(id: string): GitignoreTemplate | undefined {
  return gitignoreTemplates.find((t) => t.id === id);
}

/**
 * Get template content by ID
 */
export function getGitignoreContent(id: string): string {
  const template = getGitignoreTemplate(id);
  return template?.content ?? '';
}

/**
 * Merge multiple templates
 */
export function mergeGitignoreTemplates(ids: string[]): string {
  const contents = ids
    .map((id) => getGitignoreTemplate(id))
    .filter((t): t is GitignoreTemplate => t !== undefined)
    .map((t) => `# ===== ${t.name} =====\n${t.content}`);

  return contents.join('\n\n');
}

/**
 * Detect project type from package files
 */
export function detectProjectType(files: string[]): string[] {
  const detected: string[] = [];

  // Node.js
  if (files.some((f) => f === 'package.json' || f === 'yarn.lock' || f === 'pnpm-lock.yaml')) {
    detected.push('node');
  }

  // React / Next.js
  if (files.some((f) => f === 'next.config.js' || f === 'next.config.ts' || f === 'next.config.mjs')) {
    detected.push('react');
  }

  // Python
  if (files.some((f) => f === 'requirements.txt' || f === 'setup.py' || f === 'pyproject.toml' || f === 'Pipfile')) {
    detected.push('python');
  }

  // Rust
  if (files.some((f) => f === 'Cargo.toml' || f === 'Cargo.lock')) {
    detected.push('rust');
  }

  // Tauri
  if (files.some((f) => f === 'tauri.conf.json' || f.includes('src-tauri'))) {
    detected.push('tauri');
  }

  // Go
  if (files.some((f) => f === 'go.mod' || f === 'go.sum')) {
    detected.push('go');
  }

  // Java
  if (files.some((f) => f === 'pom.xml' || f === 'build.gradle' || f === 'build.gradle.kts')) {
    detected.push('java');
  }

  return detected.length > 0 ? detected : ['minimal'];
}

export default gitignoreTemplates;
