/**
 * Designer utilities index - Re-export all designer utilities
 */

export {
  type DesignerTemplate,
  type TemplateCategory,
  type FrameworkType,
  type CustomTemplate,
  DESIGNER_TEMPLATES,
  TEMPLATE_CATEGORIES,
  FRAMEWORK_OPTIONS,
  AI_SUGGESTIONS,
  TEMPLATE_ICONS,
  getTemplateById,
  getTemplatesByCategory,
  getTemplatesByFramework,
  getTemplatesByCategoryAndFramework,
  getDefaultTemplate,
  getRandomSuggestions,
  // Custom templates & favorites
  getCustomTemplates,
  saveCustomTemplate,
  updateCustomTemplate,
  deleteCustomTemplate,
  getFavoriteTemplateIds,
  toggleFavoriteTemplate,
  isTemplateFavorited,
  getFavoriteTemplates,
  getAllTemplates,
  searchTemplates,
  exportTemplatesAsJson,
  importTemplatesFromJson,
  duplicateTemplate,
} from './templates';

export {
  type DesignerAIConfig,
  type DesignerAIResult,
  type AISuggestionType,
  type AISuggestion,
  type AIConversationMessage,
  type QuickAIActionId,
  executeDesignerAIEdit,
  generateDesignerComponent,
  getDesignerAIConfig,
  cleanAICodeResponse,
  getAIStyleSuggestions,
  getAIAccessibilitySuggestions,
  editElementWithAI,
  continueDesignConversation,
  generateComponentVariations,
  QUICK_AI_ACTIONS,
  // New AI functions
  getAIResponsiveSuggestions,
  getAILayoutSuggestions,
  executeQuickAIAction,
  applyAISuggestions,
  getAIComponentAnalysis,
  generateTailwindClasses,
  optimizeTailwindClasses,
} from './ai';

export {
  type CDNProvider,
  type PackageInfo,
  type CDNConfig,
  type PackagePreset,
  parsePackageSpecifier,
  getCDNUrl,
  getCDNUrlWithFallback,
  batchResolveCDNUrls,
  clearCDNCache,
  getCDNCacheSize,
  generateImportMap,
  isKnownESMPackage,
  getSandpackExternalResources,
  generateSandpackDependencies,
  getPresetPackages,
  detectPackagesFromCode,
  PACKAGE_PRESETS,
} from './cdn-resolver';

export {
  type ProjectFiles,
  type ExportConfig,
  type CodeSnippet,
  normalizeSandpackFiles,
  generateViteProject,
  openInCodeSandbox,
  openInStackBlitz,
  downloadAsZip,
  downloadFile,
  copyToClipboard,
  generateShareableUrl,
  // New export functions
  createGitHubGist,
  encodeCodeForSharing,
  decodeSharedCode,
  generateCompactShareUrl,
  parseSharedUrl,
  generateEmbedCode,
  exportAsFormat,
  getQRCodeData,
  generateSocialShareLinks,
} from './export-utils';

export {
  CSS_VARIABLES,
  BASE_STYLES,
  TAILWIND_CDN_SCRIPT,
  TAILWIND_CONFIG,
  generateSandpackStyles,
  getTailwindExternalResources,
  generateStyleInjectionScript,
} from './tailwind-config';
