/**
 * Designer utilities index - Re-export all designer utilities
 * 
 * Organized into subfolders:
 * - ai/: AI-powered features (editing, analysis, generation, conversation)
 * - elements/: Element parsing and location utilities
 * - export/: Export and CDN resolution utilities
 * - config/: Templates and Tailwind configuration
 * - collaboration/: Collaboration features
 * - plugins/: Accessibility analysis utilities
 */

// AI utilities
export {
  type DesignerAIConfig,
  type DesignerAIResult,
  type AISuggestionType,
  type AISuggestion,
  type AIConversationMessage,
  type QuickAIActionId,
  executeDesignerAIEdit,
  generateDesignerComponent,
  getDesignerAIConfig,
  cleanAICodeResponse,
  getAIStyleSuggestions,
  getAIAccessibilitySuggestions,
  editElementWithAI,
  continueDesignConversation,
  generateComponentVariations,
  QUICK_AI_ACTIONS,
  getAIResponsiveSuggestions,
  getAILayoutSuggestions,
  executeQuickAIAction,
  applyAISuggestions,
  getAIComponentAnalysis,
  generateTailwindClasses,
  optimizeTailwindClasses,
  generateElementContext,
  generateTreeContext,
  resetElementCache,
  getElementCacheStats,
  findElementInCode,
  buildCodeMapping,
  getElementSourceLocation,
  // Conversation
  type AIConversation,
  type CodeDiff,
  type ConversationStreamUpdate,
  createConversation,
  addUserMessage,
  continueAIConversation,
  streamConversation,
  getConversationSummary,
  clearConversationHistory,
  // Analyzer
  type CodePattern,
  type AccessibilityIssue,
  type ResponsiveIssue,
  type CodeAnalysisResult,
  detectPatternsSimple,
  detectAccessibilityIssues,
  detectResponsiveIssues,
  analyzeCodeWithAI,
  analyzeCodeLocal,
  // Generator
  type ComponentVariant,
  type ComponentGenerationRequest,
  type GenerationResult,
  type StyleType,
  type ComponentTemplateKey,
  generateComponent,
  generateComponentVariants,
  generateVariantFromCode,
  generateComponentWithFeatures,
  generateFromTemplate,
  COMPONENT_TEMPLATES,
} from './ai';

// Element utilities
export {
  parseComponentToElement,
  isContainerElement,
  isSelfClosingElement,
  type PositioningMode,
  type SourceLocation,
  type VisualBounds,
  type DropPosition,
  type ElementLocation,
  type InsertionPoint,
  type ElementCodeMapping,
  type LocatorConfig,
  type OptimizedElementLocation,
  getVisualBounds,
  getIframeElementBounds,
  calculateDropPosition,
  calculateDropPositionHorizontal,
  findElementByPattern,
  findElementByTagAndClass,
  findClosingTag,
  parseCodeToAst,
  findElementInAst,
  buildElementCodeMapping,
  getElementLocation,
  getInsertionPoint,
  optimizeForModelOutput,
  optimizeLocationsForModel,
  generateCompactTree,
  clearAstCache,
  getAstCacheStats,
} from './elements';

// Export utilities
export {
  type CDNProvider,
  type PackageInfo,
  type CDNConfig,
  type PackagePreset,
  parsePackageSpecifier,
  getCDNUrl,
  getCDNUrlWithFallback,
  batchResolveCDNUrls,
  clearCDNCache,
  getCDNCacheSize,
  generateImportMap,
  isKnownESMPackage,
  getSandpackExternalResources,
  generateSandpackDependencies,
  getPresetPackages,
  detectPackagesFromCode,
  PACKAGE_PRESETS,
  type ProjectFiles,
  type ExportConfig,
  type CodeSnippet,
  normalizeSandpackFiles,
  generateViteProject,
  openInCodeSandbox,
  openInStackBlitz,
  downloadAsZip,
  downloadFile,
  copyToClipboard,
  generateShareableUrl,
  createGitHubGist,
  encodeCodeForSharing,
  decodeSharedCode,
  generateCompactShareUrl,
  parseSharedUrl,
  generateEmbedCode,
  exportAsFormat,
  getQRCodeData,
  generateSocialShareLinks,
} from './export';

// Config utilities
export {
  type DesignerTemplate,
  type TemplateCategory,
  type FrameworkType,
  type CustomTemplate,
  DESIGNER_TEMPLATES,
  TEMPLATE_CATEGORIES,
  FRAMEWORK_OPTIONS,
  AI_SUGGESTIONS,
  TEMPLATE_ICONS,
  getTemplateById,
  getTemplatesByCategory,
  getTemplatesByFramework,
  getTemplatesByCategoryAndFramework,
  getDefaultTemplate,
  getRandomSuggestions,
  getCustomTemplates,
  saveCustomTemplate,
  updateCustomTemplate,
  deleteCustomTemplate,
  getFavoriteTemplateIds,
  toggleFavoriteTemplate,
  isTemplateFavorited,
  getFavoriteTemplates,
  getAllTemplates,
  searchTemplates,
  exportTemplatesAsJson,
  importTemplatesFromJson,
  duplicateTemplate,
  CSS_VARIABLES,
  BASE_STYLES,
  TAILWIND_CDN_SCRIPT,
  TAILWIND_CONFIG,
  generateSandpackStyles,
  getTailwindExternalResources,
  generateStyleInjectionScript,
} from './config';

// Collaboration
export * from './collaboration';

// Plugins
export * from './plugins';
